const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];let deferredInstall=null;
function setView(name){$$('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${name}`));$$('.nav').forEach(v=>v.classList.toggle('active',v.dataset.view===name));history.replaceState(null,'',`#${name}`);window.scrollTo({top:0,behavior:'smooth'})}
function launch(){const note=$('#launchNote');if(note)note.textContent='Tentando abrir o Jarvis instalado neste computador…';location.href='jarvis://open';setTimeout(()=>{if(note)note.textContent='Se nada abriu, use “Configurar outro PC” para instalar o runtime local.'},1500)}
function isIOS(){return /iphone|ipad|ipod/i.test(navigator.userAgent)}
async function installPwa(){if(deferredInstall){deferredInstall.prompt();try{await deferredInstall.userChoice}catch{}deferredInstall=null;toggleInstallButtons(false);return}if(isIOS()){$('#iosSheet').classList.remove('hidden');return}alert('Use o menu do navegador e escolha “Instalar app” ou “Adicionar à tela inicial”.')}
function toggleInstallButtons(show=true){['#installPwaBtn','#installPwaBtn2'].forEach(sel=>{const b=$(sel);if(b)b.classList.toggle('show',show)})}
function openMobile(){let value=$('#mobileAddress').value.trim();if(!value)return alert('Digite o endereço mostrado pelo Jarvis no computador.');if(!/^https?:\/\//i.test(value))value='http://'+value;try{const u=new URL(value);if(!u.port)u.port='8770';localStorage.setItem('jarvisMobileAddress',u.href);location.href=u.href}catch{alert('Endereço inválido. Exemplo: http://192.168.0.20:8770')}}
function copy(text,button){navigator.clipboard?.writeText(text).then(()=>{const old=button.textContent;button.textContent='Copiado';setTimeout(()=>button.textContent=old,900)}).catch(()=>{})}
$$('.nav').forEach(b=>b.onclick=()=>setView(b.dataset.view));$$('[data-open-view]').forEach(b=>b.onclick=()=>setView(b.dataset.openView));$('#launchBtn').onclick=launch;$('#launchBtn2').onclick=launch;$('#copyInstall').onclick=e=>copy($('#installCommand').textContent,e.currentTarget);$('#openMobileBtn').onclick=openMobile;$('#mobileAddress').value=localStorage.getItem('jarvisMobileAddress')||'';$('#installPwaBtn').onclick=installPwa;$('#installPwaBtn2').onclick=installPwa;$('#iosClose').onclick=()=>$('#iosSheet').classList.add('hidden');$('#iosOk').onclick=()=>$('#iosSheet').classList.add('hidden');
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;toggleInstallButtons(true)});window.addEventListener('appinstalled',()=>toggleInstallButtons(false));
const initial=(location.hash||'#start').slice(1);setView(['start','mobile','install','architecture','help'].includes(initial)?initial:'start');
const params=new URLSearchParams(location.search);if(params.get('action')==='open')setTimeout(launch,250);if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(()=>{}));
