const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const presence=$('#presence'),chat=$('#chat'),form=$('#form'),input=$('#input'),historyEl=$('#history'),searchEl=$('#history-search'),titleEl=$('#conversation-title'),statusEl=$('#system-status'),modelHint=$('#model-hint'),attachmentStrip=$('#attachment-strip'),sidebar=$('#sidebar'),scrim=$('#scrim'),palette=$('#palette'),paletteInput=$('#palette-input');
let conversationId=localStorage.getItem('jarvis.conversation_id')||null,conversations=[],showArchived=false,mode=localStorage.getItem('jarvis.mode')||'auto',attachments=[],paletteIndex=0;
let prefs={refresh_ms:5000,advanced_motion:true,compact:false,default_mode:mode,'autonomy.enabled':true,'autonomy.voice_attention':true,'voice.replies':true,'voice.rate':.92,'notifications.enabled':false};
let recognition=null,voiceListening=false,voiceBase='',coreAnimator=null,hqSnapshot=null,briefingSnapshot=null,autonomySnapshot=null,lastSystem={},coreVisualState='IDLE',lastAttentionIds=new Set(),speakingToken=0,currentAudio=null,currentAudioUrl=null,pendingSpeech=null,voiceGestureUnlocked=false,voiceFailureNotified=false;
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const fmtDate=t=>{try{return new Date(t).toLocaleString('pt-BR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}catch{return ''}};
const fmtGroup=t=>{try{const d=new Date(t),n=new Date(),a=new Date(d.getFullYear(),d.getMonth(),d.getDate()),b=new Date(n.getFullYear(),n.getMonth(),n.getDate()),x=Math.round((b-a)/86400000);return x===0?'Hoje':x===1?'Ontem':x<7?'Esta semana':'Mais antigas'}catch{return 'Mais antigas'}};
const modeLabel=m=>({auto:'AUTO',fast:'RÁPIDO',deep:'DEEP',hermes:'HERMES'}[m]||'AUTO');

function markdown(raw){let s=esc(raw);s=s.replace(/```(?:[\w+-]+)?\n?([\s\S]*?)```/g,(m,c)=>`<pre>${c.trim()}</pre>`);s=s.replace(/^### (.+)$/gm,'<h3>$1</h3>').replace(/^## (.+)$/gm,'<h2>$1</h2>').replace(/^# (.+)$/gm,'<h1>$1</h1>');s=s.replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>').replace(/`([^`]+)`/g,'<code>$1</code>');s=s.replace(/\[([^\]]+)\]\((https?:\/\/[^)]+)\)/g,'<a href="$2" target="_blank" rel="noopener">$1</a>');s=s.replace(/^(?:[-*]) (.+)$/gm,'<li>$1</li>').replace(/(?:<li>[\s\S]*?<\/li>\n?)+/g,m=>`<ul>${m}</ul>`);return `<div class="md">${s.split(/\n{2,}/).map(x=>x.match(/^<(h[1-3]|ul|pre)/)?x:`<p>${x.replace(/\n/g,'<br>')}</p>`).join('')}</div>`}
function speechText(raw){return String(raw||'').replace(/```[\s\S]*?```/g,' Trecho de código omitido. ').replace(/\[([^\]]+)\]\([^)]+\)/g,'$1').replace(/[*_#>`~]/g,'').replace(/https?:\/\/\S+/g,'').replace(/\s+/g,' ').trim().slice(0,5000)}
function toast(t,c='info'){const d=document.createElement('div');d.className='toast '+c;d.textContent=t;$('#toast-stack').appendChild(d);setTimeout(()=>d.remove(),3200)}
function setComposerStatus(text=''){$('#composer-status').textContent=text}

function startCore(){const canvas=$('#jarvis-core');if(!canvas||!window.JarvisCore)return;coreAnimator?.destroy?.();coreAnimator=window.JarvisCore.create(canvas);coreAnimator.setState(coreVisualState)}
function deriveCoreState(){if((hqSnapshot?.attention||[]).some(x=>['critical','high'].includes(String(x.risk))))return 'ATTENTION';const agents=Object.values(hqSnapshot?.departments||{}).flat();if(agents.some(a=>a.status==='error'))return 'ERROR';if(agents.some(a=>a.id==='review.verifier'&&a.status==='working'))return 'VERIFYING';if(agents.some(a=>a.id==='research.general'&&a.status==='working'))return 'RESEARCHING';if(agents.some(a=>a.status==='working'))return 'EXECUTING';return 'IDLE'}
function reflectVisualState(state){coreVisualState=String(state||'IDLE').toUpperCase();$('#core-state-label').textContent=coreVisualState;$('#core-activity').textContent=({IDLE:'presente',LISTENING:'ouvindo',THINKING:'pensando',RESEARCHING:'pesquisando',EXECUTING:'executando',VERIFYING:'verificando',ATTENTION:'solicitando atenção',ERROR:'erro',SPEAKING:'falando',SUCCESS:'concluído'})[coreVisualState]||coreVisualState.toLowerCase();coreAnimator?.setState?.(coreVisualState)}
function busy(on){$('#send').disabled=on;presence.classList.toggle('busy',on);statusEl.textContent=on?'processando':'online';setComposerStatus(on?'Jarvis está pensando…':'');reflectVisualState(on?'THINKING':deriveCoreState())}

function addMessage(m,{speak=false}={}){const d=document.createElement('article');d.className='msg '+m.role;d.dataset.role=m.role;d.innerHTML=`<div class="bubble-wrap"><div class="bubble">${m.role==='assistant'?markdown(m.content):`<div class="content">${esc(m.content)}</div>`}</div><div class="meta-row">${fmtDate(m.created_at)}</div><div class="message-actions">${m.role==='assistant'?'<button data-copy>Copiar</button><button data-regenerate>Regenerar</button>':'<button data-edit>Editar</button>'}</div></div>`;d.querySelector('[data-copy]')?.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(m.content);toast('Resposta copiada.','success')}catch{toast('Falha ao copiar.','error')}});d.querySelector('[data-edit]')?.addEventListener('click',()=>{input.value=m.content;input.focus();resizeInput()});d.querySelector('[data-regenerate]')?.addEventListener('click',regenerate);chat.appendChild(d);presence.classList.add('has-messages');chat.scrollTop=chat.scrollHeight;if(speak&&m.role==='assistant')speakJarvis(m.content,{messageElement:d})}
function renderMessages(ms){chat.innerHTML='';if(!ms?.length){presence.classList.remove('has-messages');return}presence.classList.add('has-messages');ms.forEach(m=>addMessage(m));chat.scrollTop=chat.scrollHeight}

async function api(u,o){const r=await fetch(u,o);let x={};try{x=await r.json()}catch{throw new Error('Resposta inválida do servidor.')}if(!r.ok)throw new Error(x.error||String(r.status));return x}
async function loadHistory(){try{conversations=await api('/api/conversations?search='+encodeURIComponent(searchEl.value||'')+'&archived='+(showArchived?'1':'0'));const groups={};for(const c of conversations)(groups[fmtGroup(c.updated_at)]??=[]).push(c);let html='';for(const g of ['Hoje','Ontem','Esta semana','Mais antigas']){if(!groups[g])continue;html+=`<div class="history-group">${g}</div>`+groups[g].map(c=>`<button class="history-row ${c.conversation_id===conversationId?'active':''}" data-id="${esc(c.conversation_id)}"><span class="title">${c.pinned?'★ ':''}${esc(c.title)}</span><span class="sub"><span>${fmtDate(c.updated_at)}</span><span>·</span><span>${c.message_count||0} msgs</span></span></button>`).join('')}historyEl.innerHTML=html||'<div class="history-empty">Nenhuma conversa.</div>';$$('#history [data-id]').forEach(b=>b.onclick=()=>{openConversation(b.dataset.id);closeDrawer()})}catch{historyEl.innerHTML='<div class="history-empty">Histórico indisponível.</div>'}}
async function openConversation(id){const c=await api('/api/conversations/'+encodeURIComponent(id));conversationId=c.conversation_id;localStorage.setItem('jarvis.conversation_id',conversationId);titleEl.textContent=c.title;$('#pin-chat').textContent=c.pinned?'★':'☆';$('#archive-chat').textContent=c.archived?'▣':'□';renderMessages(c.messages||[]);await loadHistory()}
async function newConversation(){const x=await api('/api/conversations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:'Nova conversa'})});await openConversation(x.conversation_id);closeDrawer();input.focus()}
async function ensureConversation(){if(conversationId){try{await openConversation(conversationId);return}catch{conversationId=null;localStorage.removeItem('jarvis.conversation_id')}}const x=await api('/api/conversations?limit=1');if(x[0])await openConversation(x[0].conversation_id);else await newConversation()}

function renderAttachments(){attachmentStrip.innerHTML=attachments.map((a,i)=>`<div class="attachment-chip"><span>${esc(a.name)}</span><button data-i="${i}">×</button></div>`).join('');attachmentStrip.classList.toggle('hidden',!attachments.length);attachmentStrip.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>{attachments.splice(+b.dataset.i,1);renderAttachments()})}
async function handleFiles(fs){for(const f of [...fs].slice(0,3-attachments.length)){if(f.size>800000){toast(`${f.name} excede 800 KB.`,'error');continue}try{attachments.push({name:f.name,content:await f.text()})}catch{toast(`Não foi possível ler ${f.name}.`,'error')}}renderAttachments()}
async function send(t){t=String(t||'').trim();if(!t||$('#send').disabled)return;if(!conversationId)await newConversation();addMessage({role:'user',content:t,created_at:new Date().toISOString()});input.value='';resizeInput();busy(true);const a=attachments.map(x=>({name:x.name,content:x.content}));attachments=[];renderAttachments();try{const x=await api('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({conversation_id:conversationId,text:t,mode,attachments:a})});addMessage({role:'assistant',content:x.content,created_at:new Date().toISOString(),metadata:{agent:x.agent,model:x.model,mode:x.mode||mode}},{speak:true});modelHint.textContent=x.model||modeLabel(mode);await Promise.allSettled([loadHistory(),loadBriefing(),loadAttention(),loadSystem()]);reflectVisualState('SUCCESS');setTimeout(()=>reflectVisualState(deriveCoreState()),700)}catch(e){toast(e.message,'error');addMessage({role:'assistant',content:'Não foi possível concluir a solicitação. '+e.message,created_at:new Date().toISOString()});reflectVisualState('ERROR')}finally{busy(false)}}
async function regenerate(){busy(true);try{const x=await api('/api/conversations/'+encodeURIComponent(conversationId),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'regenerate',mode})});await openConversation(conversationId);if(x?.content)speakJarvis(x.content);toast('Resposta regenerada.','success')}catch(e){toast(e.message,'error')}finally{busy(false)}}
async function mutate(action,value){await api('/api/conversations/'+encodeURIComponent(conversationId),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...value})});await openConversation(conversationId)}
async function deleteConversation(){if(!conversationId||!confirm('Excluir esta conversa permanentemente?'))return;await api('/api/conversations/'+encodeURIComponent(conversationId),{method:'DELETE'});conversationId=null;localStorage.removeItem('jarvis.conversation_id');await ensureConversation();toast('Conversa excluída.','success')}
async function rename(){const x=prompt('Nome da conversa',titleEl.textContent);if(x!==null)await mutate('rename',{title:x})}
function exportChat(){if(!conversationId)return;const fmt=confirm('OK = Markdown\nCancelar = JSON')?'md':'json';location.href='/api/conversations/'+encodeURIComponent(conversationId)+'/export?format='+fmt}

function openDrawer(){sidebar.classList.add('open');sidebar.setAttribute('aria-hidden','false');$('#open-sidebar').setAttribute('aria-expanded','true');scrim.classList.remove('hidden')}
function closeDrawer(){sidebar.classList.remove('open');sidebar.setAttribute('aria-hidden','true');$('#open-sidebar').setAttribute('aria-expanded','false');scrim.classList.add('hidden')}
function resizeInput(){input.style.height='auto';input.style.height=Math.min(input.scrollHeight,150)+'px'}
function setMode(m){mode=m;localStorage.setItem('jarvis.mode',m);$$('#mode-switch button').forEach(b=>b.classList.toggle('active',b.dataset.mode===m));modelHint.textContent=modeLabel(m)}

async function loadBriefing(){try{briefingSnapshot=await api('/api/briefing')}catch{briefingSnapshot=null}}
async function loadSystem(){try{lastSystem=await api('/api/system');const vh=lastSystem.voice||{},tts=vh.tts||{};const label=tts.status==='healthy'?`${tts.backend||'TTS'} disponível`:'voz local opcional não configurada · fallback do navegador ativo';$('#voice-health').textContent=label}catch{$('#voice-health').textContent='Voz: fallback do navegador'}}
async function loadAutonomy(){try{autonomySnapshot=await api('/api/autonomy');$('#autonomy-status').innerHTML=`<i></i>${autonomySnapshot.enabled?'autônomo':'pausado'}`}catch{autonomySnapshot=null}}
async function approve(id){try{await api('/api/approval/'+encodeURIComponent(id)+'/approve',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});await loadAttention();toast('Aprovação processada.','success')}catch(e){toast(e.message,'error')}}
async function ackAttention(id){try{await api('/api/attention/'+encodeURIComponent(id)+'/ack',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});await loadAttention()}catch(e){toast(e.message,'error')}}
async function loadAttention(){try{const [x,notes]=await Promise.all([api('/api/hq'),api('/api/attention')]);hqSnapshot=x;$('#hq-count').textContent=x.metrics?.agents_working??'—';$('#mission-count').textContent=x.metrics?.missions_active??'—';const live=notes.filter(n=>n.status!=='acknowledged');const highest=live.find(n=>n.level==='critical')||live.find(n=>n.level==='important');const trigger=$('#open-sidebar');trigger.classList.toggle('attention',!!highest);trigger.classList.toggle('critical',highest?.level==='critical');$('#attention-panel').classList.toggle('hidden',!live.length);$('#attention-count').textContent=String(live.length);$('#attention').innerHTML=live.slice(0,5).map(n=>{const improve=n.ref_type==='improvement'&&n.ref_id;return `<div class="attention-item"><strong>${esc(n.title)}</strong><span>${esc(n.message||n.kind)}</span><div class="attention-actions">${improve?`<button class="primary" data-improve="${esc(n.ref_id)}">Aprovar melhoria</button>`:''}<button data-note="${esc(n.notification_id)}">Visto</button></div></div>`}).join('');$$('[data-note]').forEach(b=>b.onclick=()=>ackAttention(b.dataset.note));$$('[data-improve]').forEach(b=>b.onclick=async()=>{await approveImprovement(b.dataset.improve);await loadAttention()});if(highest)requestAttention(highest);reflectVisualState(deriveCoreState())}catch{}}
function requestAttention(note){if(!note)return;const id=note.notification_id||note.id;if(!id||lastAttentionIds.has(id)||sessionStorage.getItem('jarvis.attention.'+id))return;lastAttentionIds.add(id);sessionStorage.setItem('jarvis.attention.'+id,'1');if(note.level==='important'||note.level==='critical'){if(prefs['autonomy.voice_attention']!==false)speakJarvis('Senhor.',{force:true});sendSystemNotification(note.title,note.message)}}
function sendSystemNotification(title,body){if(prefs['notifications.enabled']!==true||!('Notification'in window)||Notification.permission!=='granted')return;try{new Notification(title||'Jarvis',{body:body||'Há algo que merece sua atenção.',icon:'/jarvis-icon.svg',tag:'jarvis-attention'})}catch{}}

async function runAutonomyNow(){reflectVisualState('RESEARCHING');try{await api('/api/autonomy/tick',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({force:true,scope:'curiosity'})});await Promise.all([loadAutonomy(),loadAttention(),loadBriefing()]);toast('Exploração concluída.','success')}catch(e){toast(e.message,'error')}finally{reflectVisualState(deriveCoreState())}}
async function approveImprovement(id){try{await api('/api/improvements/'+encodeURIComponent(id)+'/approve',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});await loadAutonomy()}catch(e){toast(e.message,'error')}}

function stopSpeaking(){speakingToken++;try{window.speechSynthesis?.cancel?.()}catch{}if(currentAudio){try{currentAudio.pause()}catch{}currentAudio=null}if(currentAudioUrl){try{URL.revokeObjectURL(currentAudioUrl)}catch{}currentAudioUrl=null}$$('.msg.speaking').forEach(x=>x.classList.remove('speaking'));coreAnimator?.setAudio?.(0)}
function finishSpeech(token,messageElement){if(token!==speakingToken)return;messageElement?.classList.remove('speaking');reflectVisualState(deriveCoreState());setComposerStatus('');coreAnimator?.setAudio?.(0)}
async function unlockVoice(){if(voiceGestureUnlocked)return;voiceGestureUnlocked=true;try{window.speechSynthesis?.resume?.();window.speechSynthesis?.getVoices?.()}catch{}if(pendingSpeech){const queued=pendingSpeech;pendingSpeech=null;setTimeout(()=>speakJarvis(queued.text,{force:true,messageElement:queued.messageElement}),40)}}
async function speakJarvis(raw,{force=false,messageElement=null}={}){const text=speechText(raw);if(!text||(!force&&prefs['voice.replies']===false))return;stopSpeaking();const token=++speakingToken;messageElement?.classList.add('speaking');reflectVisualState('SPEAKING');setComposerStatus('Jarvis está falando');
  try{if(await speakWithBackend(text,token,messageElement))return}catch{}
  if(speakWithBrowser(text,token,messageElement))return;
  if(await speakWithNativeWindows(text,token,messageElement))return;
  pendingSpeech={text,messageElement};finishSpeech(token,messageElement);if(!voiceFailureNotified){voiceFailureNotified=true;toast('A voz não iniciou. Clique uma vez na tela para liberar o áudio.','error')}
}
async function speakWithBackend(text,token,messageElement){let r;try{r=await fetch('/api/voice/synthesize',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text})})}catch{return false}if(!r.ok||!String(r.headers.get('content-type')||'').startsWith('audio/'))return false;const blob=await r.blob();if(token!==speakingToken)return true;currentAudioUrl=URL.createObjectURL(blob);const audio=new Audio(currentAudioUrl);currentAudio=audio;audio.preload='auto';audio.playbackRate=Math.max(.75,Math.min(1.15,Number(prefs['voice.rate'])||.92));let ctx=null,analyser=null,source=null,raf=0;try{ctx=new (window.AudioContext||window.webkitAudioContext)();await ctx.resume?.();source=ctx.createMediaElementSource(audio);analyser=ctx.createAnalyser();analyser.fftSize=64;source.connect(analyser);analyser.connect(ctx.destination);const data=new Uint8Array(analyser.frequencyBinCount);const pump=()=>{if(token!==speakingToken||audio.paused||audio.ended)return;analyser.getByteFrequencyData(data);const avg=data.reduce((a,b)=>a+b,0)/(data.length*255);coreAnimator?.setAudio?.(Math.min(1,.12+avg*2.7));raf=requestAnimationFrame(pump)};audio.addEventListener('play',pump,{once:true})}catch{}
  const done=()=>{if(raf)cancelAnimationFrame(raf);try{ctx?.close?.()}catch{}if(currentAudioUrl){try{URL.revokeObjectURL(currentAudioUrl)}catch{}currentAudioUrl=null}currentAudio=null;finishSpeech(token,messageElement)};audio.onended=done;audio.onerror=done;try{await audio.play();voiceFailureNotified=false;return true}catch{try{audio.pause()}catch{}if(raf)cancelAnimationFrame(raf);try{ctx?.close?.()}catch{}if(currentAudioUrl){try{URL.revokeObjectURL(currentAudioUrl)}catch{}currentAudioUrl=null}currentAudio=null;return false}}
function chooseBrowserVoice(){if(!('speechSynthesis'in window))return null;const voices=window.speechSynthesis.getVoices();return voices.find(v=>/pt[-_]BR/i.test(v.lang)&&/(antonio|daniel|felipe|francis|mascul|male)/i.test(v.name))||voices.find(v=>/pt[-_]BR/i.test(v.lang))||voices.find(v=>/^pt/i.test(v.lang))||null}
function speakWithBrowser(text,token,messageElement){if(!voiceGestureUnlocked||!('speechSynthesis'in window))return false;try{window.speechSynthesis.cancel();window.speechSynthesis.resume();const u=new SpeechSynthesisUtterance(text);u.lang='pt-BR';const voice=chooseBrowserVoice();if(voice)u.voice=voice;u.rate=Math.max(.75,Math.min(1.15,Number(prefs['voice.rate'])||.92));u.pitch=.88;u.volume=1;const pulse=setInterval(()=>{if(token!==speakingToken){clearInterval(pulse);return}coreAnimator?.setAudio?.(.22+Math.random()*.42)},90);const done=()=>{clearInterval(pulse);finishSpeech(token,messageElement)};u.onend=()=>{voiceFailureNotified=false;done()};u.onerror=()=>done();window.speechSynthesis.speak(u);setTimeout(()=>{if(token===speakingToken&&window.speechSynthesis.paused)window.speechSynthesis.resume()},120);return true}catch{return false}}
async function speakWithNativeWindows(text,token,messageElement){try{const r=await fetch('/api/voice/speak-native',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text})});if(!r.ok)return false;voiceFailureNotified=false;finishSpeech(token,messageElement);return true}catch{return false}}
function maybeMorningGreeting(){const now=new Date(),hour=now.getHours();if(hour<5||hour>=12)return;const key='jarvis.morning.v3.'+now.toISOString().slice(0,10);if(localStorage.getItem(key))return;const d=autonomySnapshot?.daily_briefing||{},priorities=(briefingSnapshot?.priorities||[]).length,news=(d.news||[]).length,pending=(autonomySnapshot?.improvements||[]).filter(x=>x.status==='pending').length;let parts=['Bom dia, senhor.'];if(d.weather?.summary)parts.push(d.weather.summary);if(priorities)parts.push(`Você tem ${priorities} responsabilidades em destaque.`);if(news)parts.push(`Separei ${news} notícias para hoje.`);if(pending)parts.push(`Há ${pending} melhorias minhas aguardando sua aprovação.`);localStorage.setItem(key,'1');speakJarvis(parts.join(' '),{force:true})}

function setupVoiceInput(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;const btn=$('#voice-btn');if(!SR){btn.title='Reconhecimento de voz do navegador indisponível';return}recognition=new SR();recognition.lang='pt-BR';recognition.continuous=false;recognition.interimResults=true;recognition.onstart=()=>{stopSpeaking();voiceListening=true;voiceBase=input.value.trim();btn.classList.add('active');setComposerStatus('Ouvindo…');reflectVisualState('LISTENING')};recognition.onresult=e=>{let finalText='',interim='';for(let i=e.resultIndex;i<e.results.length;i++){const t=e.results[i][0]?.transcript||'';if(e.results[i].isFinal)finalText+=t+' ';else interim+=t}if(finalText)voiceBase=(voiceBase+' '+finalText).trim();input.value=(voiceBase+' '+interim).trimStart();resizeInput()};recognition.onerror=e=>{if(e.error!=='no-speech')toast('Não foi possível ouvir.','error')};recognition.onend=()=>{voiceListening=false;btn.classList.remove('active');setComposerStatus('');reflectVisualState(deriveCoreState());if(input.value.trim()&&prefs['voice.auto_send']===true)send(input.value)};btn.onclick=()=>{if(voiceListening)recognition.stop();else{voiceBase=input.value;recognition.start()}};$('#core-zone').addEventListener('dblclick',()=>btn.click())}

function openPalette(){palette.classList.remove('hidden');paletteInput.value='';paletteIndex=0;renderPalette();setTimeout(()=>paletteInput.focus(),25)}function closePalette(){palette.classList.add('hidden')}
function renderPalette(){const q=paletteInput.value.toLowerCase().trim(),arr=[['Nova conversa','Criar conversa',newConversation],['Escritório','Abrir HQ 3D',()=>location.href='/hq'],['Missões','Mission Control',()=>location.href='/mission-control'],['Agentes','Diretório',()=>location.href='/agents'],['Projetos','Workspaces',()=>location.href='/projects'],['Memória','Contexto persistente',()=>location.href='/memory'],['Sistema','Diagnóstico',()=>location.href='/system'],['Explorar agora','Executar ciclo autônomo',runAutonomyNow],['Preferências','Configurações',()=>$('#settings-modal').showModal()],['Deep','Ativar modo Deep',()=>setMode('deep')],['Hermes','Ativar Hermes',()=>setMode('hermes')]].filter(x=>(x[0]+x[1]).toLowerCase().includes(q));palette._actions=arr;$('#palette-list').innerHTML=arr.map((x,i)=>`<button class="palette-item ${i===paletteIndex?'active':''}" data-p="${i}"><span>◇</span><span><strong>${x[0]}</strong><small>${x[1]}</small></span></button>`).join('')||'<div class="palette-item">Nada encontrado</div>';$$('#palette-list [data-p]').forEach(b=>b.onclick=()=>{arr[+b.dataset.p][2]();closePalette()})}

async function loadPrefs(){try{prefs={...prefs,...await api('/api/preferences')}}catch{}if(!localStorage.getItem('jarvis.voice.v4.migrated')){prefs['voice.replies']=true;localStorage.setItem('jarvis.voice.v4.migrated','1');try{await api('/api/preferences',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({preferences:{'voice.replies':true}})})}catch{}}$('#pref-mode').value=prefs.default_mode||mode;$('#pref-refresh').value=String(prefs.refresh_ms||5000);$('#pref-motion').checked=prefs.advanced_motion!==false;$('#pref-compact').checked=!!prefs.compact;$('#pref-autonomy').checked=prefs['autonomy.enabled']!==false;$('#pref-attention-voice').checked=prefs['autonomy.voice_attention']!==false;$('#pref-voice-replies').checked=prefs['voice.replies']!==false;$('#pref-voice-rate').value=String(prefs['voice.rate']||.92);$('#pref-location').value=prefs['autonomy.location']||'São Paulo, SP';$('#pref-notifications').checked=prefs['notifications.enabled']===true;setMode(prefs.default_mode||mode);$('#app-shell').classList.toggle('reduced-motion',prefs.advanced_motion===false)}
async function saveSettings(){prefs.default_mode=$('#pref-mode').value;prefs.refresh_ms=+$('#pref-refresh').value;prefs.advanced_motion=$('#pref-motion').checked;prefs.compact=$('#pref-compact').checked;prefs['autonomy.enabled']=$('#pref-autonomy').checked;prefs['autonomy.voice_attention']=$('#pref-attention-voice').checked;prefs['voice.replies']=$('#pref-voice-replies').checked;prefs['voice.rate']=+$('#pref-voice-rate').value;prefs['autonomy.location']=$('#pref-location').value.trim()||'São Paulo, SP';prefs['notifications.enabled']=$('#pref-notifications').checked;if(prefs['notifications.enabled']&&'Notification'in window&&Notification.permission==='default'){try{const p=await Notification.requestPermission();if(p!=='granted')prefs['notifications.enabled']=false}catch{prefs['notifications.enabled']=false}}setMode(prefs.default_mode);$('#app-shell').classList.toggle('reduced-motion',!prefs.advanced_motion);try{prefs=await api('/api/preferences',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({preferences:prefs})})}catch{}$('#settings-modal').close();toast('Preferências salvas.','success')}

$('#open-sidebar').onclick=openDrawer;$('#close-sidebar').onclick=closeDrawer;scrim.onclick=closeDrawer;$('#new-chat').onclick=newConversation;$('#history-refresh').onclick=loadHistory;searchEl.oninput=loadHistory;$('#show-archived').onclick=()=>{showArchived=!showArchived;$('#show-archived').textContent=showArchived?'Todas':'Arquivadas';loadHistory()};$('#open-settings').onclick=()=>$('#settings-modal').showModal();$('#save-settings').onclick=e=>{e.preventDefault();saveSettings()};$('#rename-chat').onclick=rename;$('#pin-chat').onclick=async()=>{const c=await api('/api/conversations/'+encodeURIComponent(conversationId));mutate('pin',{value:!c.pinned})};$('#archive-chat').onclick=async()=>{const c=await api('/api/conversations/'+encodeURIComponent(conversationId));mutate('archive',{value:!c.archived})};$('#delete-chat').onclick=deleteConversation;$('#export-chat').onclick=exportChat;$$('#mode-switch button').forEach(b=>b.onclick=()=>{$('#pref-mode').value=b.dataset.mode;setMode(b.dataset.mode)});$('#attach-btn').onclick=()=>$('#file-input').click();$('#file-input').onchange=e=>handleFiles(e.target.files);form.addEventListener('submit',e=>{e.preventDefault();send(input.value)});input.oninput=resizeInput;input.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send(input.value)}};form.ondragover=e=>{e.preventDefault();form.classList.add('dragging')};form.ondragleave=()=>form.classList.remove('dragging');form.ondrop=e=>{e.preventDefault();form.classList.remove('dragging');handleFiles(e.dataTransfer.files)};
window.addEventListener('pointerdown',unlockVoice,{once:true,capture:true});window.addEventListener('keydown',unlockVoice,{once:true,capture:true});
window.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openPalette()}if(e.ctrlKey&&e.shiftKey&&e.key.toLowerCase()==='n'){e.preventDefault();newConversation()}if(e.key==='Escape'){closePalette();closeDrawer()}});paletteInput.oninput=()=>{paletteIndex=0;renderPalette()};paletteInput.onkeydown=e=>{if(e.key==='ArrowDown'){paletteIndex=Math.min(paletteIndex+1,(palette._actions?.length||1)-1);renderPalette()}if(e.key==='ArrowUp'){paletteIndex=Math.max(0,paletteIndex-1);renderPalette()}if(e.key==='Enter'){palette._actions?.[paletteIndex]?.[2]();closePalette()}};

window.JarvisVisual?.on('agent.executing',()=>reflectVisualState('EXECUTING'));window.JarvisVisual?.on('agent.researching',()=>reflectVisualState('RESEARCHING'));window.JarvisVisual?.on('verification.started',()=>reflectVisualState('VERIFYING'));window.JarvisVisual?.on('approval.required',()=>reflectVisualState('ATTENTION'));window.JarvisVisual?.on('system.error',()=>reflectVisualState('ERROR'));

(async()=>{startCore();await loadPrefs();setupVoiceInput();await ensureConversation();await Promise.allSettled([loadHistory(),loadBriefing(),loadAttention(),loadSystem(),loadAutonomy()]);maybeMorningGreeting();const refresh=()=>Promise.allSettled([loadAttention(),loadAutonomy(),loadBriefing()]);setInterval(refresh,Math.max(3000,+prefs.refresh_ms||5000));if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});})();
