const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
let data={missions:[],attention:[],tools:[],events:[]},activeTab='missions';
function badge(s){const x=String(s||'unknown');return `<span class="badge ${esc(x)}">${esc(x)}</span>`}
function missionProgress(m){const steps=m.steps||[],done=steps.filter(s=>['completed','done','passed'].includes(s.status)).length;return steps.length?Math.round(done/steps.length*100):0}
function renderStats(){const active=data.missions.filter(x=>!['completed','failed','cancelled'].includes(x.status)).length,failed=data.missions.filter(x=>['failed','error'].includes(x.status)).length,attention=data.attention.length,running=data.tools.filter(x=>x.status==='running').length;$('#mission-stats').innerHTML=[[active,'missões ativas'],[running,'ferramentas em execução'],[attention,'pontos de atenção'],[failed,'falhas']].map(([n,l])=>`<section class="card span4"><span class="eyebrow">RUNTIME</span><strong style="font-size:22px;display:block;margin-top:4px">${n}</strong><small style="color:#61717d;font-size:8px">${l}</small></section>`).join('')}
function render(){renderStats();
 $('#missions').innerHTML=data.missions.length?data.missions.map(m=>{const p=missionProgress(m);return `<div class="row"><div style="display:flex;justify-content:space-between;gap:10px;align-items:flex-start"><b>${esc(m.title)} ${badge(m.status)}</b><span style="font-size:9px;color:#71808a">${p}%</span></div><small>${esc(m.objective)}</small><div class="progress-bar" style="height:4px;margin-top:8px"><i style="width:${p}%"></i></div><div class="actions">${(m.steps||[]).map(s=>`<span class="badge ${esc(s.status)}">${esc(s.agent_id)} · ${esc(s.status)}</span>`).join('')}</div><small>${esc(m.updated_at)} · ${esc(m.mission_id)}</small></div>`}).join(''):'<div class="empty">Nenhuma missão registrada.</div>';
 $('#attention').innerHTML=data.attention.length?data.attention.map(a=>`<div class="row"><b>${esc(a.title)} ${badge(a.kind)}</b><small>${esc(a.risk)} · ${esc(a.task_id||'')}</small>${a.kind==='approval'?`<div class="actions"><button class="secondary-action" data-approve="${esc(a.id)}">Aprovar</button><button class="secondary-action" data-reject="${esc(a.id)}">Rejeitar</button></div>`:''}</div>`).join(''):'<div class="empty">Nada aguardando você.</div>';
 $('#tools').innerHTML=data.tools.length?data.tools.slice(0,80).map(x=>`<div class="row"><b>${esc(x.tool_id)} ${badge(x.status)}</b><small>${esc(x.started_at)}${x.ended_at?' → '+esc(x.ended_at):''} · ${esc(x.error||'sem erro')}</small></div>`).join(''):'<div class="empty">Nenhuma execução.</div>';
 $('#events').innerHTML=data.events.length?data.events.slice(0,100).map(e=>`<div class="row"><b>${esc(e.event_type||e.type)} ${badge(e.severity||'info')}</b><small>${esc(e.agent_id||e.task_id||'system')} · ${esc(e.timestamp)}</small></div>`).join(''):'<div class="empty">Nenhum evento.</div>';
 document.querySelectorAll('[data-approve]').forEach(b=>b.onclick=()=>approve(b.dataset.approve));document.querySelectorAll('[data-reject]').forEach(b=>b.onclick=()=>reject(b.dataset.reject));
}
async function load(){try{const [h,t,e]=await Promise.all([fetch('/api/hq',{cache:'no-store'}).then(r=>r.json()),fetch('/api/tool-runs',{cache:'no-store'}).then(r=>r.json()),fetch('/api/events',{cache:'no-store'}).then(r=>r.json())]);data={missions:h.missions||[],attention:h.attention||[],tools:t||[],events:e||h.timeline||[]};render()}catch{}}
async function approve(id){const r=await fetch('/api/approval/'+encodeURIComponent(id)+'/approve',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});if(r.ok)load()}
async function reject(id){const r=await fetch('/api/approval/'+encodeURIComponent(id)+'/reject',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});if(r.ok)load()}
$('#refresh').onclick=load;document.querySelectorAll('#tabs button').forEach(b=>b.onclick=()=>{activeTab=b.dataset.tab;document.querySelectorAll('#tabs button').forEach(x=>x.classList.toggle('active',x===b));['missions','attention','tools','events'].forEach(k=>document.querySelector('#panel-'+k).classList.toggle('hidden',k!==activeTab))});$('#new-mission').onclick=()=>$('#mission-dialog').showModal();$('#mission-form').onsubmit=async e=>{e.preventDefault();const o=$('#mission-objective').value.trim();if(!o)return;const btn=$('#submit-mission');btn.disabled=true;try{const r=await fetch('/api/mission/team',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({objective:o,title:$('#mission-title').value.trim()||'Missão em equipe'})});const x=await r.json();if(!r.ok)throw new Error(x.error||'Falha');$('#mission-dialog').close();$('#mission-form').reset();load()}catch(err){alert(err.message)}finally{btn.disabled=false}};load();setInterval(load,2200);
