const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const chat=$('#chat'),stage=$('.stage'),input=$('#input'),form=$('#composer'),drawer=$('#drawer'),scrim=$('#scrim');
let conversationId=localStorage.getItem('jarvis.mobile.conversation_id')||null,mode=localStorage.getItem('jarvis.mode')||'auto';
let core=null,surfaceManager=null,morningController=null,speakingToken=0,currentAudio=null,currentUrl=null,voiceEnabled=localStorage.getItem('jarvis.mobile.voice')!=='0',recognition=null,deferredInstall=null,lastAttention=new Set(),typingNode=null;
let drawerTouchStart=null,lastOnline=true;
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function markdown(raw){let s=esc(raw);s=s.replace(/```(?:[\w+-]+)?\n?([\s\S]*?)```/g,(m,c)=>`<pre>${c.trim()}</pre>`).replace(/^### (.+)$/gm,'<h3>$1</h3>').replace(/^## (.+)$/gm,'<h2>$1</h2>').replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>').replace(/`([^`]+)`/g,'<code>$1</code>').replace(/^(?:[-*]) (.+)$/gm,'<li>$1</li>').replace(/(?:<li>[\s\S]*?<\/li>\n?)+/g,m=>`<ul>${m}</ul>`);return s.split(/\n{2,}/).map(x=>x.match(/^<(h[1-3]|ul|pre)/)?x:`<p>${x.replace(/\n/g,'<br>')}</p>`).join('')}
function speechText(v){return String(v||'').replace(/```[\s\S]*?```/g,' Trecho de código omitido. ').replace(/\[([^\]]+)\]\([^)]+\)/g,'$1').replace(/[*_#>`~]/g,'').replace(/https?:\/\/\S+/g,'').replace(/\s+/g,' ').trim().slice(0,5000)}
function toast(t,c=''){const d=document.createElement('div');d.className='toast '+c;d.textContent=t;$('#toasts').appendChild(d);setTimeout(()=>d.remove(),3200)}
function haptic(pattern=10){try{if('vibrate'in navigator)navigator.vibrate(pattern)}catch{}}
async function api(u,o){const r=await fetch(u,o);let x={};try{x=await r.json()}catch{throw new Error('Resposta inválida.')}if(!r.ok)throw new Error(x.error||String(r.status));return x}
async function streamApi(payload,{onDelta,onStatus}={}){const r=await fetch('/api/chat/stream',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!r.ok){let x={};try{x=await r.json()}catch{}throw new Error(x.error||String(r.status))}if(!r.body)throw new Error('Streaming indisponível.');const reader=r.body.getReader(),decoder=new TextDecoder();let buffer='',doneResult=null;while(true){const {value,done}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});let nl;while((nl=buffer.indexOf('\n'))>=0){const line=buffer.slice(0,nl).trim();buffer=buffer.slice(nl+1);if(!line)continue;let event;try{event=JSON.parse(line)}catch{continue}if(event.type==='delta')onDelta?.(event.text||'');else if(event.type==='status')onStatus?.(event.stage||'working');else if(event.type==='error')throw new Error(event.error||'Falha durante streaming.');else if(event.type==='done')doneResult=event.result||{};}}return doneResult||{};}
function beginStreamMessage(){hideTyping();const a=document.createElement('article');a.className='msg assistant streaming';a.innerHTML='<div class="bubble"><span class="stream-content"></span></div>';chat.appendChild(a);stage.classList.add('has-messages');chat.scrollTop=chat.scrollHeight;return a}
function paintStreamMessage(node,text,final=false){const b=node.querySelector('.bubble');if(final){b.innerHTML=markdown(text);node.classList.remove('streaming')}else{const c=node.querySelector('.stream-content');if(c)c.textContent=text}chat.scrollTop=chat.scrollHeight}
function startSurfaces(){const root=$('#surface-layer');if(!root||!window.JarvisUI)return;surfaceManager=window.JarvisUI.create(root,{max:1,onChange:state=>stage.classList.toggle('surface-active',state.count>0)})}
function bindSurfaceBacked(node){if(!node)return;node.classList.add('surface-backed')}
function presentSurfaces(surfaces,node,{restoring=false}={}){if(!surfaceManager)return;const list=Array.isArray(surfaces)?surfaces.filter(Boolean):[];if(!list.length){if(!restoring)surfaceManager.clear();return}surfaceManager.present(list);bindSurfaceBacked(node);core?.setAudio?.(.9);haptic([6,28,6])}

function setState(s,label){s=String(s||'IDLE').toUpperCase();core?.setState?.(s);const caption=label||({IDLE:'presente',LISTENING:'ouvindo',THINKING:'pensando',RESEARCHING:'pesquisando',EXECUTING:'executando',SPEAKING:'falando',ATTENTION:'atenção',ERROR:'erro',SUCCESS:'concluído'})[s]||s.toLowerCase();$('#core-caption').textContent=caption;$('#state-label').textContent=s==='IDLE'?'PRESENTE':s;stage.classList.toggle('busy',!['IDLE','SUCCESS'].includes(s));document.documentElement.dataset.jarvisState=s.toLowerCase()}
function resize(){input.style.height='auto';input.style.height=Math.min(118,input.scrollHeight)+'px'}
function showTyping(){hideTyping();typingNode=document.createElement('article');typingNode.className='msg assistant typing';typingNode.innerHTML='<div class="bubble"><i></i><i></i><i></i></div>';chat.appendChild(typingNode);stage.classList.add('has-messages');chat.scrollTop=chat.scrollHeight}
function hideTyping(){typingNode?.remove();typingNode=null}
function addMessage(m,{speak=false}={}){hideTyping();const a=document.createElement('article');a.className='msg '+m.role;a.innerHTML=`<div class="bubble">${m.role==='assistant'?markdown(m.content):esc(m.content)}</div>`;chat.appendChild(a);stage.classList.add('has-messages');requestAnimationFrame(()=>chat.scrollTo({top:chat.scrollHeight,behavior:'smooth'}));if(speak&&m.role==='assistant')speakJarvis(m.content)}
function renderMessages(ms){hideTyping();chat.innerHTML='';const visible=(ms||[]).filter(m=>!(m.role==='assistant'&&m.metadata?.kind==='morning_sequence'));if(!visible.length){stage.classList.remove('has-messages');surfaceManager?.clear();return}stage.classList.add('has-messages');visible.forEach(m=>addMessage(m));const latest=[...visible].reverse().find(m=>m.role==='assistant'&&m.metadata?.surfaces?.length);if(latest)presentSurfaces(latest.metadata.surfaces,null,{restoring:true});else surfaceManager?.clear();chat.scrollTop=chat.scrollHeight}
async function newConversation(){const x=await api('/api/conversations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:'Nova conversa'})});conversationId=x.conversation_id;localStorage.setItem('jarvis.mobile.conversation_id',conversationId);renderMessages([]);await loadHistory();closeMenu();input.focus();haptic(8)}
async function openConversation(id){const c=await api('/api/conversations/'+encodeURIComponent(id));conversationId=c.conversation_id;localStorage.setItem('jarvis.mobile.conversation_id',conversationId);renderMessages(c.messages||[]);await loadHistory();closeMenu()}
async function ensureConversation(){if(conversationId){try{await openConversation(conversationId);return}catch{}}const list=await api('/api/conversations');if(list[0])await openConversation(list[0].conversation_id);else await newConversation()}
async function loadHistory(){try{const list=await api('/api/conversations');$('#conversation-count').textContent=String(list.length||0);$('#history').innerHTML=list.slice(0,22).map(c=>`<button data-id="${esc(c.conversation_id)}" class="${c.conversation_id===conversationId?'active':''}"><b>${esc(c.title)}</b><span>${c.message_count||0} mensagens</span></button>`).join('')||'<div class="note"><span>Nenhuma conversa.</span></div>';$$('#history [data-id]').forEach(b=>b.onclick=()=>openConversation(b.dataset.id))}catch{}}
function isMorningSequenceCommand(value){const q=String(value||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');if(!q.includes('briefing'))return false;return ['faca','refaca','inicie','iniciar','execute','executar','rode','rodar','mostre','mostrar','abra','abrir','completo','completa','do dia','de hoje','manha'].some(x=>q.includes(x))}
async function send(text){text=String(text||'').trim();if(!text||$('#send-btn').disabled)return;if(!conversationId)await newConversation();surfaceManager?.clear();addMessage({role:'user',content:text});input.value='';resize();$('#send-btn').disabled=true;$('#composer-status').textContent='Jarvis está pensando…';setState('THINKING');showTyping();haptic(6);const streamNode=beginStreamMessage();let streamed='',painted='',queued=false;const paint=()=>{queued=false;if(streamed!==painted){painted=streamed;paintStreamMessage(streamNode,painted,false)}};try{const x=await streamApi({conversation_id:conversationId,text,mode,attachments:[]},{onDelta:d=>{streamed+=d;if(!queued){queued=true;requestAnimationFrame(paint)}},onStatus:stageName=>{const labels={research:'pesquisando…',developer:'desenvolvendo…',team_mission:'coordenando…',reasoning:'raciocinando…',generating:'respondendo…'};$('#composer-status').textContent=labels[stageName]||'Jarvis está trabalhando…';if(stageName==='research')setState('RESEARCHING');else if(stageName==='generating')setState('THINKING')}});if(x.kind==='morning_sequence'||x.ui_action==='morning_sequence'){streamNode.remove();hideTyping();await runMorningSequence(true);loadHistory();return}if(!streamed)streamed=x.content||'';paintStreamMessage(streamNode,streamed,true);presentSurfaces(x.surfaces,streamNode);if(voiceEnabled)speakJarvis(x.surfaces?.[0]?.voice_summary||streamed);$('#model-state').textContent=x.model||mode.toUpperCase();const ttft=x.performance?.ttft_ms;if(ttft!=null)$('#model-state').title=`Primeiro token: ${Math.round(ttft)} ms`;setState('SUCCESS');haptic([8,35,8]);setTimeout(refreshState,750);loadHistory()}catch(e){streamNode.remove();hideTyping();toast(e.message,'error');setState('ERROR');haptic([20,30,20])}finally{$('#send-btn').disabled=false;$('#composer-status').textContent=''}}
function stopSpeech(){speakingToken++;try{currentAudio?.pause()}catch{}currentAudio=null;if(currentUrl){URL.revokeObjectURL(currentUrl);currentUrl=null}try{speechSynthesis?.cancel()}catch{}core?.setAudio?.(0)}
async function speakJarvis(raw){if(!voiceEnabled)return;const text=speechText(raw);if(!text)return;stopSpeech();const token=++speakingToken;setState('SPEAKING');try{const r=await fetch('/api/voice/synthesize',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text})});if(r.ok&&String(r.headers.get('content-type')||'').startsWith('audio/')){const blob=await r.blob();if(token!==speakingToken)return;currentUrl=URL.createObjectURL(blob);const audio=new Audio(currentUrl);currentAudio=audio;audio.preload='auto';let ctx,analyser,raf=0;try{ctx=new(window.AudioContext||window.webkitAudioContext)();await ctx.resume();const src=ctx.createMediaElementSource(audio),dry=ctx.createGain(),delay=ctx.createDelay(.05),wet=ctx.createGain(),hp=ctx.createBiquadFilter();hp.type='highpass';hp.frequency.value=85;delay.delayTime.value=.008;dry.gain.value=.92;wet.gain.value=.08;analyser=ctx.createAnalyser();analyser.fftSize=64;src.connect(hp);hp.connect(dry);hp.connect(delay);delay.connect(wet);dry.connect(analyser);wet.connect(analyser);analyser.connect(ctx.destination);const data=new Uint8Array(analyser.frequencyBinCount);const pump=()=>{if(audio.paused||audio.ended||token!==speakingToken)return;analyser.getByteFrequencyData(data);const avg=data.reduce((a,b)=>a+b,0)/(data.length*255);core?.setAudio?.(Math.min(1,.14+avg*2.6));raf=requestAnimationFrame(pump)};audio.addEventListener('play',pump,{once:true})}catch{}const done=()=>{if(raf)cancelAnimationFrame(raf);try{ctx?.close()}catch{}if(currentUrl){URL.revokeObjectURL(currentUrl);currentUrl=null}currentAudio=null;setState('IDLE')};audio.onended=done;audio.onerror=done;await audio.play();return}}catch{}
  if('speechSynthesis'in window){try{const u=new SpeechSynthesisUtterance(text);u.lang='pt-BR';const vs=speechSynthesis.getVoices();u.voice=vs.find(v=>/pt[-_]BR/i.test(v.lang)&&/(antonio|daniel|male|mascul)/i.test(v.name))||vs.find(v=>/pt[-_]BR/i.test(v.lang))||null;u.rate=.93;u.pitch=.82;u.onend=()=>setState('IDLE');speechSynthesis.cancel();speechSynthesis.speak(u);return}catch{}}
  setState('IDLE');toast('Áudio indisponível neste navegador.','error')
}
function setupMic(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){$('#mic-btn').onclick=()=>toast(location.protocol==='https:'?'Reconhecimento de voz não é suportado neste navegador.':'Use o acesso HTTPS seguro para habilitar o microfone no celular.','error');return}recognition=new SR();recognition.lang='pt-BR';recognition.continuous=false;recognition.interimResults=true;recognition.onstart=()=>{stopSpeech();$('#mic-btn').classList.add('listening');$('#composer-status').textContent='Ouvindo…';setState('LISTENING');haptic(8)};recognition.onresult=e=>{let finalText='',interim='';for(let i=e.resultIndex;i<e.results.length;i++){const t=e.results[i][0]?.transcript||'';if(e.results[i].isFinal)finalText+=t+' ';else interim+=t}input.value=(finalText+interim).trimStart();resize()};recognition.onend=()=>{$('#mic-btn').classList.remove('listening');$('#composer-status').textContent='';setState('IDLE');if(input.value.trim())send(input.value)};recognition.onerror=e=>{if(e.error!=='no-speech')toast('Não consegui ouvir.','error')};$('#mic-btn').onclick=()=>{stopSpeech();try{recognition.start()}catch{}}}
async function loadAttention(){try{const notes=(await api('/api/attention')).filter(n=>n.status!=='acknowledged');$('#attention-count').textContent=String(notes.length||0);$('#attention').innerHTML=notes.slice(0,8).map(n=>`<div class="note ${esc(n.level||'')}"><b>${esc(n.title)}</b><span>${esc(n.message||n.kind||'')}</span></div>`).join('')||'<div class="note"><span>Nada pedindo atenção.</span></div>';const important=notes.find(n=>['important','critical'].includes(n.level));if(important&&!lastAttention.has(important.notification_id)){lastAttention.add(important.notification_id);haptic(important.level==='critical'?[20,50,20]:12);if(voiceEnabled)speakJarvis('Senhor.')}}catch{}}
function setOnline(ok){lastOnline=ok;$('#network-banner').classList.toggle('hidden',ok);$('#connection-state').textContent=ok?'conectado':'offline';$('.connection-led')?.style.setProperty('background',ok?'var(--green)':'var(--red)')}
async function refreshState(){try{const x=await api('/api/hq');setOnline(true);const agents=Object.values(x.departments||{}).flat();if((x.attention||[]).some(n=>['critical','high'].includes(String(n.risk))))setState('ATTENTION');else if(agents.some(a=>a.status==='error'))setState('ERROR');else if(agents.some(a=>a.id==='research.general'&&a.status==='working'))setState('RESEARCHING');else if(agents.some(a=>a.status==='working'))setState('EXECUTING');else setState('IDLE')}catch{setOnline(false);setState('ERROR')}}
function openMenu(){drawer.classList.add('open');drawer.setAttribute('aria-hidden','false');scrim.classList.remove('hidden');loadHistory();loadAttention();haptic(5)}function closeMenu(){drawer.classList.remove('open');drawer.setAttribute('aria-hidden','true');scrim.classList.add('hidden')}
function setupViewport(){const update=()=>{const vv=window.visualViewport;if(!vv){document.documentElement.style.setProperty('--vvh','100dvh');document.documentElement.style.setProperty('--keyboard-offset','0px');return}const h=Math.max(320,vv.height);const keyboard=Math.max(0,window.innerHeight-vv.height-vv.offsetTop);document.documentElement.style.setProperty('--vvh',h+'px');document.documentElement.style.setProperty('--keyboard-offset',keyboard+'px')};update();window.visualViewport?.addEventListener('resize',update);window.visualViewport?.addEventListener('scroll',update);window.addEventListener('orientationchange',()=>setTimeout(update,150))}
function setupDrawerGestures(){document.addEventListener('touchstart',e=>{const t=e.touches[0];drawerTouchStart={x:t.clientX,y:t.clientY,time:performance.now(),open:drawer.classList.contains('open')}},{passive:true});document.addEventListener('touchend',e=>{if(!drawerTouchStart)return;const t=e.changedTouches[0],dx=t.clientX-drawerTouchStart.x,dy=Math.abs(t.clientY-drawerTouchStart.y);if(dy<75&&performance.now()-drawerTouchStart.time<650){if(!drawerTouchStart.open&&drawerTouchStart.x<24&&dx>72)openMenu();if(drawerTouchStart.open&&dx<-72)closeMenu()}drawerTouchStart=null},{passive:true})}
async function runMorningSequence(force=false){if(!window.JarvisMorning)return false;if(!morningController)morningController=window.JarvisMorning.create({hostSelector:'.stage',speak:speakJarvis,setState,focusInput:()=>input.focus()});if(!morningController.shouldRun(force))return false;try{morningController.beginPreparing?.();const seq=await morningController.prepare(force);return await morningController.start(seq,{force})}catch(e){morningController.finish?.();toast('Briefing indisponível: '+e.message,'error');return false}}
$('#replay-morning').onclick=()=>{closeMenu();runMorningSequence(true)};
$('#menu-btn').onclick=openMenu;$('#close-menu').onclick=closeMenu;scrim.onclick=closeMenu;$('#new-chat').onclick=newConversation;$('#refresh-btn').onclick=()=>Promise.allSettled([refreshState(),loadAttention(),loadHistory()]);$('#test-voice').onclick=()=>speakJarvis('Estou ouvindo, senhor. Jarvis está conectado ao seu celular.');
$('#voice-toggle').onclick=()=>{voiceEnabled=!voiceEnabled;localStorage.setItem('jarvis.mobile.voice',voiceEnabled?'1':'0');$('#voice-toggle').classList.toggle('active',voiceEnabled);if(!voiceEnabled)stopSpeech();toast(voiceEnabled?'Voz ativada.':'Voz silenciada.');haptic(6)};
form.onsubmit=e=>{e.preventDefault();send(input.value)};input.oninput=resize;input.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send(input.value)}};window.addEventListener('online',()=>{setOnline(true);refreshState()});window.addEventListener('offline',()=>setOnline(false));
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;$('#install-btn').classList.remove('hidden')});$('#install-btn').onclick=async()=>{if(!deferredInstall)return;deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;$('#install-btn').classList.add('hidden')};
(async()=>{setupViewport();setupDrawerGestures();core=window.JarvisCore?.create?.($('#jarvis-core'),{quality:'mobile'});startSurfaces();setState('IDLE');setOnline(navigator.onLine!==false);$('#voice-toggle').classList.toggle('active',voiceEnabled);setupMic();if(window.JarvisMorning)morningController=window.JarvisMorning.create({hostSelector:'.stage',speak:speakJarvis,setState,focusInput:()=>input.focus()});const bootPromise=morningController?.bootProgress?.();await ensureConversation();const morningPrefetch=(morningController?.shouldRun?.(false))?morningController.prepare(false).catch(()=>null):Promise.resolve(null);await Promise.allSettled([refreshState(),loadAttention()]);await bootPromise;const morningData=await morningPrefetch;if(morningController&&!morningController.skipped)morningController.finishBoot(false);if(morningData&&morningController&&!morningController.skipped)await morningController.start(morningData);const tick=async()=>{if(!document.hidden)await Promise.allSettled([refreshState(),loadAttention()]);setTimeout(tick,document.hidden?15000:6500)};setTimeout(tick,6500);document.addEventListener('visibilitychange',()=>{if(!document.hidden)Promise.allSettled([refreshState(),loadAttention()])});if('serviceWorker'in navigator&&location.protocol==='https:')navigator.serviceWorker.register('/sw.js').catch(()=>{})})();
