const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const chat=$('#chat'),stage=$('.stage'),input=$('#input'),form=$('#composer'),drawer=$('#drawer'),scrim=$('#scrim');
let conversationId=localStorage.getItem('jarvis.mobile.conversation_id')||null,mode=localStorage.getItem('jarvis.mode')||'auto';
let core=null,speakingToken=0,currentAudio=null,currentUrl=null,voiceEnabled=localStorage.getItem('jarvis.mobile.voice')!=='0',recognition=null,deferredInstall=null,lastAttention=new Set();
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function markdown(raw){let s=esc(raw);s=s.replace(/```(?:[\w+-]+)?\n?([\s\S]*?)```/g,(m,c)=>`<pre>${c.trim()}</pre>`).replace(/^### (.+)$/gm,'<h3>$1</h3>').replace(/^## (.+)$/gm,'<h2>$1</h2>').replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>').replace(/`([^`]+)`/g,'<code>$1</code>').replace(/^(?:[-*]) (.+)$/gm,'<li>$1</li>').replace(/(?:<li>[\s\S]*?<\/li>\n?)+/g,m=>`<ul>${m}</ul>`);return s.split(/\n{2,}/).map(x=>x.match(/^<(h[1-3]|ul|pre)/)?x:`<p>${x.replace(/\n/g,'<br>')}</p>`).join('')}
function speechText(v){return String(v||'').replace(/```[\s\S]*?```/g,' Trecho de código omitido. ').replace(/\[([^\]]+)\]\([^)]+\)/g,'$1').replace(/[*_#>`~]/g,'').replace(/https?:\/\/\S+/g,'').replace(/\s+/g,' ').trim().slice(0,5000)}
function toast(t,c=''){const d=document.createElement('div');d.className='toast '+c;d.textContent=t;$('#toasts').appendChild(d);setTimeout(()=>d.remove(),3000)}
async function api(u,o){const r=await fetch(u,o);let x={};try{x=await r.json()}catch{throw new Error('Resposta inválida.')}if(!r.ok)throw new Error(x.error||String(r.status));return x}
function setState(s,label){s=String(s||'IDLE').toUpperCase();core?.setState?.(s);$('#core-caption').textContent=label||({IDLE:'presente',LISTENING:'ouvindo',THINKING:'pensando',RESEARCHING:'pesquisando',EXECUTING:'executando',SPEAKING:'falando',ATTENTION:'atenção',ERROR:'erro',SUCCESS:'concluído'})[s]||s.toLowerCase();$('#state-label').textContent=s==='IDLE'?'PRESENTE':s}
function resize(){input.style.height='auto';input.style.height=Math.min(120,input.scrollHeight)+'px'}
function addMessage(m,{speak=false}={}){const a=document.createElement('article');a.className='msg '+m.role;a.innerHTML=`<div class="bubble">${m.role==='assistant'?markdown(m.content):esc(m.content)}</div>`;chat.appendChild(a);stage.classList.add('has-messages');chat.scrollTop=chat.scrollHeight;if(speak&&m.role==='assistant')speakJarvis(m.content)}
function renderMessages(ms){chat.innerHTML='';if(!ms?.length){stage.classList.remove('has-messages');return}stage.classList.add('has-messages');ms.forEach(addMessage);chat.scrollTop=chat.scrollHeight}
async function newConversation(){const x=await api('/api/conversations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:'Nova conversa'})});conversationId=x.conversation_id;localStorage.setItem('jarvis.mobile.conversation_id',conversationId);renderMessages([]);await loadHistory();closeMenu();input.focus()}
async function openConversation(id){const c=await api('/api/conversations/'+encodeURIComponent(id));conversationId=c.conversation_id;localStorage.setItem('jarvis.mobile.conversation_id',conversationId);renderMessages(c.messages||[]);await loadHistory();closeMenu()}
async function ensureConversation(){if(conversationId){try{await openConversation(conversationId);return}catch{}}const list=await api('/api/conversations');if(list[0])await openConversation(list[0].conversation_id);else await newConversation()}
async function loadHistory(){try{const list=await api('/api/conversations');$('#history').innerHTML=list.slice(0,20).map(c=>`<button data-id="${esc(c.conversation_id)}" class="${c.conversation_id===conversationId?'active':''}"><b>${esc(c.title)}</b><span>${c.message_count||0} mensagens</span></button>`).join('')||'<div class="note"><span>Nenhuma conversa.</span></div>';$$('#history [data-id]').forEach(b=>b.onclick=()=>openConversation(b.dataset.id))}catch{}}
async function send(text){text=String(text||'').trim();if(!text||$('#send-btn').disabled)return;if(!conversationId)await newConversation();addMessage({role:'user',content:text});input.value='';resize();$('#send-btn').disabled=true;$('#composer-status').textContent='Jarvis está pensando…';setState('THINKING');try{const x=await api('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({conversation_id:conversationId,text,mode,attachments:[]})});addMessage({role:'assistant',content:x.content},{speak:true});$('#model-state').textContent=x.model||mode.toUpperCase();setState('SUCCESS');setTimeout(refreshState,700);loadHistory()}catch(e){toast(e.message,'error');setState('ERROR')}finally{$('#send-btn').disabled=false;$('#composer-status').textContent=''}}
function stopSpeech(){speakingToken++;try{currentAudio?.pause()}catch{}currentAudio=null;if(currentUrl){URL.revokeObjectURL(currentUrl);currentUrl=null}try{speechSynthesis?.cancel()}catch{}core?.setAudio?.(0)}
async function speakJarvis(raw){if(!voiceEnabled)return;const text=speechText(raw);if(!text)return;stopSpeech();const token=++speakingToken;setState('SPEAKING');try{const r=await fetch('/api/voice/synthesize',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text})});if(r.ok&&String(r.headers.get('content-type')||'').startsWith('audio/')){const blob=await r.blob();if(token!==speakingToken)return;currentUrl=URL.createObjectURL(blob);const audio=new Audio(currentUrl);currentAudio=audio;audio.preload='auto';let ctx,analyser,raf=0;try{ctx=new(window.AudioContext||window.webkitAudioContext)();await ctx.resume();const src=ctx.createMediaElementSource(audio),dry=ctx.createGain(),delay=ctx.createDelay(.05),wet=ctx.createGain(),hp=ctx.createBiquadFilter();hp.type='highpass';hp.frequency.value=85;delay.delayTime.value=.008;dry.gain.value=.92;wet.gain.value=.08;analyser=ctx.createAnalyser();analyser.fftSize=64;src.connect(hp);hp.connect(dry);hp.connect(delay);delay.connect(wet);dry.connect(analyser);wet.connect(analyser);analyser.connect(ctx.destination);const data=new Uint8Array(analyser.frequencyBinCount);const pump=()=>{if(audio.paused||audio.ended||token!==speakingToken)return;analyser.getByteFrequencyData(data);const avg=data.reduce((a,b)=>a+b,0)/(data.length*255);core?.setAudio?.(Math.min(1,.14+avg*2.6));raf=requestAnimationFrame(pump)};audio.addEventListener('play',pump,{once:true})}catch{}const done=()=>{if(raf)cancelAnimationFrame(raf);try{ctx?.close()}catch{}if(currentUrl){URL.revokeObjectURL(currentUrl);currentUrl=null}currentAudio=null;setState('IDLE')};audio.onended=done;audio.onerror=done;await audio.play();return}}catch{}
  if('speechSynthesis'in window){try{const u=new SpeechSynthesisUtterance(text);u.lang='pt-BR';const vs=speechSynthesis.getVoices();u.voice=vs.find(v=>/pt[-_]BR/i.test(v.lang)&&/(antonio|daniel|male|mascul)/i.test(v.name))||vs.find(v=>/pt[-_]BR/i.test(v.lang))||null;u.rate=.93;u.pitch=.82;u.onend=()=>setState('IDLE');speechSynthesis.cancel();speechSynthesis.speak(u);return}catch{}}
  setState('IDLE');toast('Áudio indisponível neste navegador.','error')
}
function setupMic(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){$('#mic-btn').onclick=()=>toast(location.protocol==='https:'?'Reconhecimento de voz não é suportado neste navegador.':'Use o acesso HTTPS seguro para habilitar o microfone no celular.','error');return}recognition=new SR();recognition.lang='pt-BR';recognition.continuous=false;recognition.interimResults=true;recognition.onstart=()=>{$('#mic-btn').classList.add('listening');$('#composer-status').textContent='Ouvindo…';setState('LISTENING')};recognition.onresult=e=>{let t='';for(let i=e.resultIndex;i<e.results.length;i++)t+=e.results[i][0]?.transcript||'';input.value=t;resize()};recognition.onend=()=>{$('#mic-btn').classList.remove('listening');$('#composer-status').textContent='';setState('IDLE');if(input.value.trim())send(input.value)};recognition.onerror=()=>toast('Não consegui ouvir.','error');$('#mic-btn').onclick=()=>{stopSpeech();try{recognition.start()}catch{}}}
async function loadAttention(){try{const notes=(await api('/api/attention')).filter(n=>n.status!=='acknowledged');$('#attention').innerHTML=notes.slice(0,8).map(n=>`<div class="note ${esc(n.level||'')}"><b>${esc(n.title)}</b><span>${esc(n.message||n.kind||'')}</span></div>`).join('')||'<div class="note"><span>Nada pedindo atenção.</span></div>';const important=notes.find(n=>['important','critical'].includes(n.level));if(important&&!lastAttention.has(important.notification_id)){lastAttention.add(important.notification_id);if(voiceEnabled)speakJarvis('Senhor.')}}catch{}}
async function refreshState(){try{const x=await api('/api/hq');const agents=Object.values(x.departments||{}).flat();if((x.attention||[]).some(n=>['critical','high'].includes(String(n.risk))))setState('ATTENTION');else if(agents.some(a=>a.status==='error'))setState('ERROR');else if(agents.some(a=>a.id==='research.general'&&a.status==='working'))setState('RESEARCHING');else if(agents.some(a=>a.status==='working'))setState('EXECUTING');else setState('IDLE');$('#connection-state').textContent='conectado'}catch{$('#connection-state').textContent='offline';setState('ERROR')}}
function openMenu(){drawer.classList.add('open');drawer.setAttribute('aria-hidden','false');scrim.classList.remove('hidden');loadHistory();loadAttention()}function closeMenu(){drawer.classList.remove('open');drawer.setAttribute('aria-hidden','true');scrim.classList.add('hidden')}
$('#menu-btn').onclick=openMenu;$('#close-menu').onclick=closeMenu;scrim.onclick=closeMenu;$('#new-chat').onclick=newConversation;$('#refresh-btn').onclick=()=>Promise.allSettled([refreshState(),loadAttention(),loadHistory()]);$('#test-voice').onclick=()=>speakJarvis('Estou ouvindo, senhor. Jarvis está conectado ao seu celular.');
$('#voice-toggle').onclick=()=>{voiceEnabled=!voiceEnabled;localStorage.setItem('jarvis.mobile.voice',voiceEnabled?'1':'0');$('#voice-toggle').classList.toggle('active',voiceEnabled);if(!voiceEnabled)stopSpeech();toast(voiceEnabled?'Voz ativada.':'Voz silenciada.')};
form.onsubmit=e=>{e.preventDefault();send(input.value)};input.oninput=resize;input.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send(input.value)}};window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;$('#install-btn').classList.remove('hidden')});$('#install-btn').onclick=async()=>{if(!deferredInstall)return;deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;$('#install-btn').classList.add('hidden')};
(async()=>{core=window.JarvisCore?.create?.($('#jarvis-core'));setState('IDLE');$('#voice-toggle').classList.toggle('active',voiceEnabled);setupMic();await ensureConversation();await Promise.allSettled([refreshState(),loadAttention()]);setInterval(()=>Promise.allSettled([refreshState(),loadAttention()]),5000);if('serviceWorker'in navigator&&location.protocol==='https:')navigator.serviceWorker.register('/sw.js').catch(()=>{})})();
