const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const canvas=$('#office-canvas'), stage=$('#stage'), fallback=$('#fallback'), labelsEl=$('#room-labels');
let THREE,OrbitControls; try{THREE=await import('three');({OrbitControls}=await import('three/addons/controls/OrbitControls.js'))}catch(err){console.error(err);fallback.classList.remove('hidden');throw err}
let renderer,scene,camera,controls,raycaster,mouse,state=null,autoRotate=true,last=performance.now(),selected=null; const clickable=[];const roomMap=new Map();const agentObjects=new Map();const animated=[];
const ROOM_LAYOUT={Research:[-11,-7],Intelligence:[0,-7],Creative:[11,-7],Engineering:[-11,7],Command:[0,7],Operations:[11,7],Review:[-11,21],Administration:[0,21],Memory:[11,21]};
const PALETTE={room:0x0d151d,glass:0x5f87a7,desk:0x3a2a20,wood:0x6b4b35,metal:0x7e8b96,screen:0x76b9ff,green:0x72d9a7,amber:0xe5ba70,red:0xef707c,floor:0x121920,accent:0x5fa9e8,wall:0x1e2933};
function mat(c,o=.7,m=.1,e=0){const mtl=new THREE.MeshStandardMaterial({color:c,roughness:o,metalness:m});if(e){mtl.emissive=new THREE.Color(c);mtl.emissiveIntensity=e}return mtl}
function box(w,h,d,c,r=.72,m=.1,e=0){return new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat(c,r,m,e))}function cyl(r,h,c){return new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,20),mat(c,.62,.18))}function sph(r,c,e=0){return new THREE.Mesh(new THREE.SphereGeometry(r,20,14),mat(c,.55,.12,e))}
function glow(c,i=1,s=1){return new THREE.PointLight(c,i,s,2)}
function statusColor(s){return s==='working'?PALETTE.screen:s==='error'?PALETTE.red:s==='needs_input'?PALETTE.amber:PALETTE.green}
function addObject(o,parent=scene){parent.add(o);return o}
function makeScreen(parent,x,y,z,w=.9,h=.55,color=PALETTE.screen){const frame=box(w+.12,h+.12,.06,0x10161c,.35,.4);frame.position.set(x,y,z);parent.add(frame);const screen=box(w,h,.025,color,.3,.25,1.6);screen.position.set(x,y,z-.045);parent.add(screen);animated.push({type:'screen',obj:screen,phase:Math.random()*6})}
function makeDesk(g,ox,oz){const d=new THREE.Group();d.position.set(ox,.35,oz);const top=box(2.25,.14,1.05,PALETTE.wood,.65,.1);top.position.y=.45;d.add(top);for(const x of[-.9,.9])for(const z of[-.36,.36]){const leg=box(.11,.7,.11,PALETTE.metal,.5,.6);leg.position.set(x,.02,z);d.add(leg)};makeScreen(d,0,1.1,-.25,.95,.56,PALETTE.screen);const kb=box(.55,.03,.22,0x20252a,.7,.3);kb.position.set(0,.55,.2);d.add(kb);const chair=cyl(.38,.08,0x20282e);chair.position.set(0,.28,.88);d.add(chair);const stem=box(.06,.32,.06,PALETTE.metal,.4,.7);stem.position.set(0,.12,.88);d.add(stem);const lamp=box(.05,.48,.05,PALETTE.metal,.5,.5);lamp.position.set(.9,.73,.35);lamp.rotation.z=-.22;d.add(lamp);const bulb=sph(.07,PALETTE.amber,1.5);bulb.position.set(.98,.47,.36);d.add(bulb);g.add(d);return d}
function makePerson(g,color,status='idle'){const p=new THREE.Group();p.userData={type:'agent'};const c=statusColor(status);const body=cyl(.25,.62,color);body.position.y=.82;p.add(body);const head=sph(.22,0xe1bda0);head.position.y=1.35;p.add(head);const hair=sph(.23,0x24272b);hair.scale.y=.48;hair.position.set(0,1.49,0);p.add(hair);for(const x of[-.11,.11]){const leg=box(.08,.42, .1,0x1d232a,.65,.15);leg.position.set(x,.31,0);p.add(leg)}const ring=new THREE.Mesh(new THREE.TorusGeometry(.33,.028,8,28),mat(c,.35,.25,1.4));ring.rotation.x=Math.PI/2;ring.position.y=.16;p.add(ring);p.userData.statusRing=ring;animated.push({type:'agent',obj:p,phase:Math.random()*6});g.add(p);return p}
function makePlant(g,x,z){const pot=cyl(.18,.32,0x473629);pot.position.set(x,.22,z);g.add(pot);for(let i=0;i<6;i++){const leaf=sph(.15,0x2c6a50,.5);leaf.scale.set(.45,1.8,.45);leaf.position.set(x+Math.cos(i)*.12,.55,z+Math.sin(i)*.12);leaf.rotation.z=Math.cos(i)*.7;g.add(leaf)}}
function makeRoom(name,pos){const g=new THREE.Group();g.position.set(pos[0],0,pos[1]);g.userData={type:'room',room:name};roomMap.set(name,g);clickable.push(g);const zone=box(9.4,.08,7.8,PALETTE.room,.94,.02);zone.position.y=.06;g.add(zone);const rug=box(7.4,.025,5.8,0x171f28,.98,.02);rug.position.y=.11;g.add(rug);const back=box(9.4,2.1,.12,PALETTE.wall,.8,.3);back.position.set(0,1.05,-3.85);g.add(back);if(name!=='Command'){for(let x=-3;x<=3;x+=2){makeScreen(g,x,.92,-3.75,.85,.48,name==='Engineering'?0x84b8ff:name==='Creative'?0xe7a1c2:0x79c8a1)}for(const z of[-1.45,1.2])for(const x of[-2.25,.3,2.25])makeDesk(g,x,z)}else{makePlant(g,-3.5,-2.7);makePlant(g,3.5,-2.7)}makePlant(g,-3.9,2.8);makePlant(g,3.9,2.8);const status=statusColor(state?.departments?.[name]?.[0]?.status);const lamp=glow(status,2.1,7);lamp.position.set(0,2.2,0);g.add(lamp);buildGlassWalls(g,name);return g}
function buildGlassWalls(g,name){const wallMat=mat(0x7896aa,.18,.35);wallMat.transparent=true;wallMat.opacity=.24;for(const x of[-4.7,4.7]){const w=box(.06,2.15,7.6,0x617f94,.2,.3);w.material=wallMat.clone();w.position.set(x,1.05,0);g.add(w)}for(const z of[-3.8,3.8]){const w=box(9.4,2.15,.06,0x617f94,.2,.3);w.material=wallMat.clone();w.position.set(0,1.05,z);g.add(w)}// door gap illusion
const door=box(1.2,1.95,.08,0x19303f,.16,.4);door.position.set(0,1,-3.76);door.material.transparent=true;door.material.opacity=.3;g.add(door)}
function buildCommand(g){const base=cyl(3.8,.35,0x101a22);base.position.y=.2;g.add(base);const inner=cyl(2.7,.08,0x162738);inner.position.y=.39;g.add(inner);for(let r=1.5;r<=3;r+=.75){const tor=new THREE.Mesh(new THREE.TorusGeometry(r,.025,8,80),mat(r===3?0x5fa9e8:0x45657d,.5,.35,1));tor.rotation.x=Math.PI/2;tor.position.y=.48;g.add(tor);animated.push({type:'ring',obj:tor,dir:r%1.5?1:-1})}const core=sph(1.0,0x143e62,2);core.position.y=1.12;g.add(core);const core2=sph(.54,0xa7e2ff,4);core2.position.y=1.12;g.add(core2);const light=glow(0x62b8ff,10,18);light.position.y=1.6;g.add(light);const holo=new THREE.Mesh(new THREE.CylinderGeometry(2.1,2.1,.015,64,1,true),mat(0x4c9dd9,.35,.15,1));holo.material.transparent=true;holo.material.opacity=.16;holo.position.y=1.8;g.add(holo);animated.push({type:'core',obj:core,phase:0});}
function buildScene(){scene.add(new THREE.HemisphereLight(0xbcd6ed,0x101114,1.65));const key=new THREE.DirectionalLight(0xffffff,2.3);key.position.set(8,25,4);key.castShadow=true;key.shadow.mapSize.set(2048,2048);scene.add(key);const warm=glow(0xffbd7a,24,60);warm.position.set(-5,8,12);scene.add(warm);const cool=glow(0x5aaeff,18,50);cool.position.set(8,9,-8);scene.add(cool);scene.fog=new THREE.Fog(0x060a0f,40,85);
 const floor=box(36,.55,42,PALETTE.floor,.96,.18);floor.position.set(0,-.32,7);floor.receiveShadow=true;scene.add(floor);for(let x=-18;x<=18;x+=2){const l=box(.012,.012,42,0x26323d,.98,.1);l.position.set(x,-.015,7);scene.add(l)}for(let z=-14;z<=28;z+=2){const l=box(36,.012,.012,0x26323d,.98,.1);l.position.set(0,-.014,z);scene.add(l)}
 for(let x=-11;x<=11;x+=11){for(let z=-7;z<=21;z+=14){const name=['Research','Intelligence','Creative','Engineering','Command','Operations','Review','Administration','Memory'][((x+11)/11)+(z===-7?0:z===7?3:6)];makeRoom(name,ROOM_LAYOUT[name])}}
 for(const g of roomMap.values())scene.add(g);
 // Re-create room map correctly because nested index expression above is deliberately simple.
 scene.children.filter(o=>o.userData?.type==='room').forEach(o=>{});
 const command=roomMap.get('Command');buildCommand(command);command.userData={type:'command'};clickable.push(command);for(const [name,g] of roomMap){const strip=box(7.4,.025,.07,0x3d8dc5,.25,.3,1.4);strip.position.set(0,.13,-3.42);g.add(strip)}
 buildPerimeter();
}
function buildPerimeter(){const roof=box(36,.18,42,0x0b1015,.9,.3);roof.position.set(0,5.2,7);roof.material.transparent=true;roof.material.opacity=.2;scene.add(roof);for(let x=-15;x<=15;x+=5){const strip=box(2.5,.035,.08,0x3a586e,.25,.3,1.5);strip.position.set(x,4.8,-13.8);scene.add(strip)}for(const z of[-13.7,27.7]){const wall=box(36,5,.18,0x131c24,.78,.28);wall.position.set(0,2.5,z);scene.add(wall)}}
function addLabels(){for(const room of Object.keys(ROOM_LAYOUT)){const d=document.createElement('div');d.className='room-label';d.dataset.room=room;d.innerHTML=`<b>${esc(room)}</b><span>carregando</span>`;labelsEl.appendChild(d)}}
function projectLabels(){for(const el of labelsEl.children){const obj=roomMap.get(el.dataset.room);if(!obj)continue;const p=obj.getWorldPosition(new THREE.Vector3(0,2.8,0));p.project(camera);el.style.left=`${(p.x*.5+.5)*stage.clientWidth}px`;el.style.top=`${(-p.y*.5+.5)*stage.clientHeight}px`;}}
function bind(){stage.addEventListener('pointerdown',click);$('#auto-rotate').onclick=e=>{autoRotate=!autoRotate;e.currentTarget.classList.toggle('active',autoRotate)};$('#reset-view').onclick=()=>setCamera([29,25,34],[0,2,7]);$('#preset-overview').onclick=()=>setCamera([29,25,34],[0,2,7]);$('#preset-command').onclick=()=>setCamera([14,10,16],[0,1,7]);$('#preset-floor').onclick=()=>setCamera([0,31,10],[0,0,7]);$('#zoom-in').onclick=()=>controls.dollyIn(1.18);$('#zoom-out').onclick=()=>controls.dollyOut(1.18);window.addEventListener('resize',resize);$('[data-room]')?.addEventListener('click',()=>{});}
function click(e){const r=canvas.getBoundingClientRect();mouse.x=((e.clientX-r.left)/r.width)*2-1;mouse.y=-((e.clientY-r.top)/r.height)*2+1;raycaster.setFromCamera(mouse,camera);const hit=raycaster.intersectObjects(clickable,true)[0];if(!hit)return;let o=hit.object;while(o.parent&&!o.userData?.type)o=o.parent;if(o.userData?.type==='agent'){selectAgent(o)}else if(o.userData?.type==='room'){selectRoom(o.userData.room)}else if(o.userData?.type==='command'){selectCommand()}}
function selectCommand(){selected=null;$('#selected-title').textContent='Command Core';$('#selected-subtitle').textContent='central orchestration';$('#selected-status').textContent='READY';$('#selected-detail').innerHTML='<b>Jarvis Core</b><br><br>Centro de orquestração. Model Router, memória, agentes, ferramentas e verificação convergem aqui.<br><br><span>Interativo: sim · fonte: backend</span>'}
function findAgent(id){return Object.values(state?.departments||{}).flat().find(a=>a.id===id)}
function selectAgentObj(id){const a=findAgent(id);if(!a)return;$('#selected-title').textContent=a.name;$('#selected-subtitle').textContent=`${a.department} · ${a.id}`;$('#selected-status').textContent=String(a.status||'idle').toUpperCase();$('#selected-detail').innerHTML=`<b>${esc(a.activity||'Disponível')}</b><br><br>Modelo: ${esc(a.model||'—')}<br>Progresso: ${Math.round((a.progress||0)*100)}%<br>Task: ${esc(a.task_id||'—')}<br><br>${esc(a.mission||'')}`}
function selectAgent(obj){const id=obj.userData.agentId;selected=obj;selectAgentObj(id)}
function selectRoom(name){const agents=state?.departments?.[name]||[];$('#selected-title').textContent=name;$('#selected-subtitle').textContent=`${agents.length} agente(s)`;$('#selected-status').textContent=agents.some(a=>a.status==='working')?'WORKING':'READY';$('#selected-detail').innerHTML=(agents.map(a=>`<b>${esc(a.name)}</b> · ${esc(a.status)}<br><span>${esc(a.activity||'Disponível')}</span>`).join('<br><br>')||'Nenhum agente')} 
function renderState(data){state=data;const m=data.metrics||{};$('#summary').innerHTML=`<div class="metric"><strong>${m.agents_available||0}</strong><span>disponíveis</span></div><div class="metric"><strong>${m.agents_working||0}</strong><span>trabalhando</span></div><div class="metric"><strong>${m.missions_active||0}</strong><span>missões</span></div><div class="metric"><strong>${m.needs_you||0}</strong><span>atenções</span></div>`;$('#mission-total').textContent=String((data.missions||[]).length);$('#attention-count').textContent=String((data.attention||[]).length);$('#missions').innerHTML=(data.missions||[]).slice(0,5).map(x=>`<div class="mission-item"><strong>${esc(x.title)}</strong><small>${esc(x.status)} · ${(x.steps||[]).length} etapas</small><div class="progress-bar"><i style="width:${Math.min(100,Math.max(0,Math.round(((x.steps||[]).filter(s=>s.status==='completed').length/Math.max(1,(x.steps||[]).length))*100)))}%"></i></div></div>`).join('')||'<div class="muted-count">Nenhuma missão.</div>';$('#attention').innerHTML=(data.attention||[]).slice(0,4).map(x=>`<div class="attention-item"><strong>${esc(x.title)}</strong><small>${esc(x.kind)} · ${esc(x.risk)}</small>${x.kind==='approval'?`<button data-approve="${esc(x.id)}">Aprovar</button>`:''}</div>`).join('')||'<div class="muted-count">Nada pendente.</div>';$('#attention').querySelectorAll('[data-approve]').forEach(b=>b.onclick=approve);
 $('#department-nav').innerHTML=Object.entries(data.departments||{}).map(([name,agents])=>`<button class="dept-btn" data-dept="${esc(name)}"><b>${esc(name)}</b><span>${agents.length} estação(ões)</span></button>`).join('');$('#department-nav').querySelectorAll('[data-dept]').forEach(b=>b.onclick=()=>{selectRoom(b.dataset.dept);focusRoom(b.dataset.dept)});
 document.querySelector('#connection').textContent='ONLINE';document.querySelector('#version').textContent=data.schema||'LIVE';if(!scene.userData.agentsBuilt){scene.userData.agentsBuilt=true;buildAgents()}syncAgents();syncLabels()}
function syncLabels(){for(const el of labelsEl.children){const a=state?.departments?.[el.dataset.room]||[];const working=a.filter(x=>x.status==='working').length;el.querySelector('span').textContent=working?`${working} trabalhando`:`${a.length} estação(ões)`}}
function syncAgents(){for(const [id,obj] of agentObjects){const a=findAgent(id);if(!a)continue;const ring=obj.userData.statusRing;ring.material.color.setHex(statusColor(a.status));ring.material.emissive.setHex(statusColor(a.status));ring.material.emissiveIntensity=a.status==='working'?2.6:1;}}
function buildAgents(){for(const [name,g] of roomMap){const agents=state?.departments?.[name]||[];if(!agents.length)continue;const positions=[[-2.0,1.25],[1.5,1.2],[-.1,2.0]];agents.forEach((a,i)=>{const p=makePerson(g,0x42515e,a.status);const pos=positions[i%positions.length];p.position.set(pos[0],0,pos[1]);p.userData.agentId=a.id;agentObjects.set(a.id,p);clickable.push(p)})}}
function setCamera(pos,target){camera.position.set(...pos);controls.target.set(...target);controls.update()}
function focusRoom(name){const g=roomMap.get(name);if(!g)return;const world=g.getWorldPosition(new THREE.Vector3());setCamera([world.x+8,9,world.z+10],[world.x,1,world.z])}
async function approve(e){const id=e.currentTarget?.dataset?.approve||e.dataset?.approve;try{const r=await fetch('/api/approval/'+encodeURIComponent(id)+'/approve',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});if(!r.ok)throw new Error();load()}catch{}}
async function load(){try{const r=await fetch('/api/hq',{cache:'no-store'});if(!r.ok)throw new Error();const x=await r.json();renderState(x)}catch{document.querySelector('#connection').textContent='OFFLINE'}}
function resize(){const w=stage.clientWidth,h=stage.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}
function animate(now=performance.now()){const dt=Math.min(.05,(now-last)/1000);last=now;if(autoRotate){camera.position.applyAxisAngle(new THREE.Vector3(0,1,0),dt*.035);controls.update()}for(const a of animated){if(a.type==='screen'){a.obj.material.emissiveIntensity=1.25+Math.sin(now*.002+a.phase)*.16}else if(a.type==='agent'){a.obj.position.y=Math.sin(now*.0016+a.phase)*.025;const r=a.obj.userData.statusRing;r.rotation.z+=dt*(a.obj.userData.statusRing.material.emissiveIntensity>1?1.2:.3)}else if(a.type==='ring'){a.obj.rotation.z+=dt*.08*a.dir}else if(a.type==='core'){a.obj.position.y=1.12+Math.sin(now*.002)*.05}}controls.update();renderer.render(scene,camera);projectLabels();requestAnimationFrame(animate)}
renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.8));scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(43,1,.1,160);controls=new OrbitControls(camera,canvas);controls.enableDamping=true;controls.dampingFactor=.06;controls.minDistance=13;controls.maxDistance=70;controls.maxPolarAngle=Math.PI/2.02;controls.target.set(0,2,7);raycaster=new THREE.Raycaster();mouse=new THREE.Vector2();
buildScene();addLabels();bind();setCamera([29,25,34],[0,2,7]);resize();load();setInterval(load,2200);requestAnimationFrame(animate);
