from typing import Protocol
class Executor(Protocol):
    async def execute(self, action: dict) -> dict: ...
class Observer(Protocol):
    async def observe(self, target: dict) -> dict: ...
class Verifier(Protocol):
    async def verify(self, expected: dict, evidence: dict) -> dict: ...
